# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.
EXTRA_CXXFLAGS = -Og -g -flto
APP_NAME := oop
ARDUINO_LIBS :=
include ~/Development/arduino/libraries/EpoxyDuino/EpoxyDuino.mk
