repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-ast
    -   id: check-illegal-windows-names
    -   id: check-toml
    -   id: trailing-whitespace
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        name: codespell
        args: ["--exclude-file=tests/util/all.lst,uv.lock", "--skip=*.atdf,*.atdf.orig,*.svd",
          "-L ser, RCALL, datas, rcall, ACI, EXTINT, THT, SEH, socio-economic"]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        require_serial: true
        args: ["-rn", "-sn", "--ignore-pattern=((attiny|atmega|at90|avr16|avr32|avr64|avr128|avr256).*\\.py)", "--ignore=harvest.py,alldevices.py,collect.py",
          "--disable=similarities,import-error"]
    -   id: unittest
        name: unittest
        entry: uv run python -m unittest discover
        language: system
        types: [python]
        args: []
        pass_filenames: false
    -   id: typecheck
        name: typecheck
        entry: uv run mypy
        language: system
        types: [python]
        args: []