#pylint: disable=missing-module-docstring
# Clock combinations and naming
micro_clock = {'1.2' : ('1M2', '1200000UL'), '9.6' : ('9M6', '9600000UL'),
      '16' : ('16M', '16000000UL')}
mini_clock = {'1' : ('1MHz_internal', '1000000UL'), '4' : ('4MHz_internal', '4000000UL'),
      '8' : ('8MHz_internal', '8000000UL'),
      '16' : ('16MHz_external', '16000000UL')}
tiny_updi_clock = {'1' : ('1internal', '1000000UL'), '4' : ('4internal', '4000000UL'),
      '8' : ('8internal', '8000000UL'),
      '16' : ('16internal', '16000000UL'),
      '20' : ('20internal', '20000000UL')}
updi_clock = {'1' : ('internal_1MHz', '1000000UL'), '4' : ('internal_4MHz', '4000000UL'),
      '8' : ('internal_8MHz', '8000000UL'),
      '16' : ('internal_16MHz', '16000000UL'),
      '20' : ('internal_20MHz', '20000000UL')}
attiny_rc_clock = {'1' : ('1MHz_internal', '1000000UL'), '4' : ('4MHz_internal', '4000000UL'),
      '8' : ('8MHz_internal', '8000000UL')}
attiny_clock = mini_clock
attiny_pll_clock =  {'1' : ('1MHz_internal', '1000000UL'), '4' : ('4MHz_internal', '4000000UL'),
      '8' : ('8MHz_internal', '8000000UL'),
      '16' : ('16MHz_external', '16000000UL'), '16i' : ('16MHz_internal_PLL', '16000000UL') }
c_clock = {'1' : '1000000UL', '8' : '8000000UL', '16' : '16000000UL', '20' : '20000000UL'}
no_clock = {'none' : ('', '16000000UL')}

# Tag list: for each tag in the list for one device, this tag has to be present in the script tag list
# Example: For attiny13 only scripts are selected that have  'small', 'arduino', 'dw', and 'noadc' in their description
test_devices = {"attiny13" : (micro_clock, ('small', 'arduino', 'dw', 'noadc', 'noautopc'),
                                   "MicroCore:avr:13:clock=", "Dev Board"),
                "attiny2313" : (attiny_clock, ('small',  'dw', 'noadc', 'noautopc'),
                                   "TinyCore:avr:x313:chip=2313,clock=", "Programmer-ZF"),
                "attiny2313a" : (attiny_clock, ('small',  'dw', 'noadc', 'noautopc'),
                                   "TinyCore:avr:x313:chip=2313,clock=", "Programmer-ZF"),
                "attiny4313" : (attiny_clock, ('medium',  'dw', 'noadc', 'noautopc'),
                                   "TinyCore:avr:x313:chip=4313,clock=", "Programmer-ZF"),
                "attiny43u" : (attiny_rc_clock,  ('medium', 'dw', 'noautopc', 'noadc'),
                                   "TinyCore:avr:43:clock=", "Breakout Board"), # changed name with v2.0.0!
                "attiny24" : (attiny_clock, ('small',  'dw', 'noautopc'),
                                   "TinyCore:avr:x4:chip=24,clock=", "Dev Board"),
                "attiny44" : (attiny_clock, ('medium',  'dw', 'noautopc'),
                                   "TinyCore:avr:x4:chip=44,clock=", "Dev Board"),
                "attiny84" : (attiny_clock, ('large',   'dw', 'noautopc'),
                                   "TinyCore:avr:x4:chip=84,clock=", "Dev Board"),
                "attiny841" : (attiny_rc_clock, ('large',   'dw', 'noautopc'),
                                   "TinyCore:avr:x41:chip=841,clock=", "Breakout Board"),
                "attiny441" : (attiny_rc_clock, ('medium',  'dw', 'noautopc'),
                                   "TinyCore:avr:x41:chip=441,clock=", "Breadboard setup"),
                "attiny25" : (attiny_pll_clock, ('small',   'dw', 'noautopc'),
                                   "TinyCore:avr:x5:chip=25,clock=", "Dev Board"),
                "attiny45" : (attiny_pll_clock, ('medium',  'dw', 'noautopc'),
                                   "TinyCore:avr:x5:chip=45,clock=", "Dev Board"),
                "attiny85" : (attiny_pll_clock, ('large', 'dw', 'noautopc'),
                                   "TinyCore:avr:x5:chip=85,clock=", "Dev Board"),
                "attiny261" : (attiny_clock, ('small',  'dw', 'noautopc'),
                                    "TinyCore:avr:x61:chip=261,clock=", "Dev Board"),
                "attiny461" : (attiny_pll_clock, ('medium',   'dw', 'noautopc'),
                                    "TinyCore:avr:x61:chip=461,clock=", "Dev Board"),
                "attiny861" : (attiny_pll_clock, ('large',   'dw', 'noautopc'),
                                    "TinyCore:avr:x61:chip=861,clock=", "Dev Board"),
                "attiny87" : (attiny_clock, ('large',  'dw', 'noautopc'),
                                   "TinyCore:avr:x7:chip=87,clock=", "Breakout Board"),
                "attiny167" : (attiny_clock, ('large',  'dw', 'noautopc'),
                                    "TinyCore:avr:x7:chip=167,clock=", "Breakout Board"),
                "attiny48" : (attiny_rc_clock, ('medium',  'dw', 'noautopc'),
                                   "TinyCore:avr:x8:chip=48,clock=", "Programmer-ZF"),
                "attiny88" : (attiny_rc_clock, ('large',  'dw', 'noautopc'),
                                   "TinyCore:avr:x8:chip=88,clock=", "Programmer-ZF"),
                "attiny828" : (attiny_rc_clock, ('large',   'dw', 'noautopc'),
                                    "TinyCore:avr:828:clock=", "Breakout Board"),
                "attiny1634" : (attiny_rc_clock, ('large',  'dw', 'noautopc'),
                                     "TinyCore:avr:1634:clock=", "Breakout Board"),
                "atmega48" : (mini_clock, ('dirty', 'dw'),
                                    "MiniCore:avr:48:variant=modelNonP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega48a" : (mini_clock, ('medium',  'dw', 'noautopc'),
                                    "MiniCore:avr:48:variant=modelNonP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega48p" : (mini_clock, ('medium',  'dw', 'noautopc'),
                                    "MiniCore:avr:48:variant=modelP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega48pa" : (mini_clock, ('medium',  'dw', 'noautopc'),
                                    "MiniCore:avr:48:variant=modelP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega48pb" : (mini_clock, ('medium',  'dw', 'noautopc'),
                                    "MiniCore:avr:48:variant=modelPB,bootloader=no_bootloader," +
                                    "clock=", "TQFP socket on breadboard"),
                "atmega88" : (mini_clock, ('dw', 'dirty'),
                                    "MiniCore:avr:88:variant=modelNonP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega88a" : (mini_clock, ('large', 'arduino', 'dw', 'noautopc'),
                                    "MiniCore:avr:88:variant=modelNonP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega88p" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:88:variant=modelP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega88pa" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:88:variant=modelP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega88pb" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:88:variant=modelPB,bootloader=no_bootloader,clock=",
                                    "TQFP socket on breadboard"),
                "atmega168" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:168:variant=modelNonP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega168a" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:168:variant=modelNonP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega168p" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:168:variant=modelP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF / XPLAINED Mini Board"),
                "atmega168pa" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:168:variant=modelP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega328" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:328:variant=modelNonP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega328p" : (mini_clock, ('large',  'dw'),
                                    "MiniCore:avr:328:variant=modelP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZIF"),
                "atmega328pb" : (mini_clock, ('large',  'dw'),
                                    "MiniCore:avr:328:variant=modelPB,bootloader=no_bootloader,clock=",
                                     "XPLAINED Mini Board"),
                "atmega168pb" : (mini_clock, ('large',  'dw'),
                                    "MiniCore:avr:168:variant=modelPB,bootloader=no_bootloader,clock=",
                                    "TQFP socket on breadboard / XPLAINED Mini Board"),

                # debugWIRE targets with no Core support
                "at90usb162" : (c_clock, ('large', 'nonarduino', 'dw', 'noadc', 'noautopc'), "",
                                    "AVR-USB-162 Olimex board"),

                # JTAG targets: MightyCore
                "atmega16" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:16:bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega16a" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:16:bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega32" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:32:bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega164pa" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:164:variant=modelP,bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega324p" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:324:variant=modelP,bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega644" : (mini_clock, ('large',  'jtag'),
                                     "MightyCore:avr:644:variant=modelA,bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega1284p" : (mini_clock, ('huge',  'jtag'),
                                     "MightyCore:avr:1284:variant=modelP,bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega324pb" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:324:variant=modelPB,bootloader=no_bootloader,clock=",
                                     "XPLAINED Pro Board"),

                # JTAG targets: MegaCore
                "atmega2560": (mini_clock, ('huge',  'jtag'),
                                   "MegaCore:avr:2560:bootloader=no_bootloader,clock=",
                                   "Arduino Mega"),
                "atmega1280": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:1280:bootloader=no_bootloader,clock=",
                                   "Arduino Mega 1280"),
                "atmega640": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:640:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega169p": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:169:variant=modelP,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega329p": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:329:variant=model329P,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega649a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:649:variant=model649,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega3290a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:329:variant=model3290,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega6490a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:649:variant=model6490,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega64": (mini_clock, ('large', 'jtag'),
                                   "MegaCore:avr:64:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega128": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:128:bootloader=no_bootloader,clock=",
                                   "Olimex AVR-MT-128 or Enplas socket"),
                "atmega1281": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:1281:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega2561": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:2561:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "at90can64": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:can64:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "at90can32": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:can32:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "at90can128": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:can128:bootloader=no_bootloader,clock=",
                                   "Olimex AVR-CAN"),
                "atmega165pa": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:165:variant=modelP,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega325a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:325:variant=model325,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega645a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:645:variant=model645,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega3250pa": (mini_clock, ('large', 'jtag'),
                                   "MegaCore:avr:325:variant=model3250P,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega6450a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:645:variant=model6450,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),


                # JTAG targets: MajorCore
                "atmega162": (mini_clock, ('large',  'jtag', 'noadc'),
                                   "MajorCore:avr:162:bootloader=no_bootloader,clock=",
                                   "Breadboard"),

                # JTAG targets: Arduino AVR Core
                "atmega32u4": (no_clock, ('large', 'jtag'),
                                   "arduino:avr:leonardo",
                                   "Leonardo"),

                # UPDI targets: MegaCoreX
                "atmega4809": (updi_clock, ('large', 'updi', 'noadc'),
                                   "MegaCoreX:megaavr:4809:bootloader=no_bootloader,clock=",
                                   "Curiosity Nano or Uno WiFi Rev2 or Nano Every"),

                "atmega3209": (updi_clock, ('large', 'updi', 'noadc'),
                                   "MegaCoreX:megaavr:3209:bootloader=no_bootloader,clock=",
                                   "QFP48 socket"),
                "atmega1609": (updi_clock, ('large', 'updi', 'noadc'),
                                   "MegaCoreX:megaavr:1609:bootloader=no_bootloader,clock=",
                                   "QFP48 socket"),
                "atmega809": (updi_clock, ('large', 'updi', 'noadc'),
                                   "MegaCoreX:megaavr:809:bootloader=no_bootloader,clock=",
                                   "QFP48 socket"),

                "atmega4808": (updi_clock, ('large', 'updi', 'noadc'),
                                   "MegaCoreX:megaavr:4808:bootloader=no_bootloader,clock=",
                                   "Thinary Nano Every"),

                "atmega3208": (updi_clock, ('large', 'updi', 'noadc'),
                                   "MegaCoreX:megaavr:3208:bootloader=no_bootloader,clock=",
                                   "QFP32 socket"),

                "atmega1608": (updi_clock, ('large', 'updi', 'noadc'),
                                   "MegaCoreX:megaavr:1608:bootloader=no_bootloader,clock=",
                                   "QFP32 socket"),

                "atmega808": (updi_clock, ('large', 'updi', 'noadc'),
                                   "MegaCoreX:megaavr:808:bootloader=no_bootloader,clock=",
                                   "QFP32 socket"),

                # UPDI targets: tinyMegaCore
                "attiny202": (tiny_updi_clock, ('small', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy2:chip=202,clock=",
                                   "SOIC8 narrow socket"),
                "attiny212": (tiny_updi_clock, ('small', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy2:chip=212,clock=",
                                   "SOIC8 narrow socket"),
                "attiny402": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy2:chip=402,clock=",
                                   "SOIC8 narrow socket"),
                "attiny412": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy2:chip=412,clock=",
                                   "SOIC8 narrow socket"),
                "attiny204": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=204,clock=",
                                   "SOIC14 narrow socket"),
                "attiny214": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=214,clock=",
                                   "SOIC14 narrow socket"),
                "attiny404": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=404,clock=",
                                   "SOIC14 narrow socket"),
                "attiny414": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=414,clock=",
                                   "SOIC14 narrow socket"),
                "attiny424": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=424,clock=",
                                   "SOIC14 narrow socket"),
                "attiny804": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=804,clock=",
                                   "SOIC14 narrow socket"),
                "attiny814": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=814,clock=",
                                   "SOIC14 narrow socket"),
                "attiny824": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=824,clock=",
                                   "SOIC14 narrow socket"),
                "attiny1604": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=1604,clock=",
                                   "SOIC14 narrow socket"),
                "attiny1614": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=1614,clock=",
                                   "SOIC14 narrow socket"),
                "attiny1624": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=1624,clock=",
                                   "SOIC14 narrow socket"),
                "attiny3224": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy4:chip=3224,clock=",
                                   "SOIC14 narrow socket"),
                "attiny406": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=406,clock=",
                                   "SOIC20 socket"),
                "attiny416": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=416,clock=",
                                   "SOIC20 socket"),
                "attiny426": (tiny_updi_clock, ('medium', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=426,clock=",
                                   "SOIC20 socket"),
                "attiny806": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=806,clock=",
                                   "SOIC20 socket"),
                "attiny816": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=816,clock=",
                                   "SOIC20 socket"),
                "attiny826": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=826,clock=",
                                   "SOIC20 socket"),
                "attiny817": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy7:chip=817,clock=",
                                   "Adafruit Seesaw ATtiny817"),
                "attiny1606": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=1606,clock=",
                                   "Adafruit Seesaw Attiny1606"),
                "attiny1616": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=1616,clock=",
                                   "Adafruit Seesaw Attiny1616"),
                "attiny1626": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=1626,clock=",
                                   "SOIC20 socket"),
                "attiny1607": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy7:chip=1607,clock=",
                                   "Curiosity Nano ATtiny1607"),
                "attiny3216": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=3216,clock=",
                                   "SOIC20 socket"),
                "attiny3226": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy6:chip=3226,clock=",
                                   "Breakout board"),
                "attiny3217": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy7:chip=3217,clock=",
                                   "Curiosity Nano"),
                "attiny3227": (tiny_updi_clock, ('large', 'updi', 'noadc'),
                                   "megaTinyCore:megaavr:atxy7:chip=3227,clock=",
                                   "Curiosity Nano"),

                # UPDI-targets: Dx Ex Lx Sx devices


                "avr32da28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrda:chip=avr32da28,clock=",
                                   "Breadboard"),
                "avr64da28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrda:chip=avr64da28,clock=",
                                   "Breadboard"),
                "avr128da28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrda:chip=avr128da28,clock=",
                                   "Breadboard"),
                "avr128da48":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrda:chip=avr128da48,clock=",
                                   "Curiosity Nano"),
                "avr32db28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdb:chip=avr32db28,clock=",
                                   "Breadboard"),
                "avr64db28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdb:chip=avr64db28,clock=",
                                   "Breadboard"),
                "avr128db28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdb:chip=avr128db28,clock=",
                                   "Breadboard"),
                "avr128db48":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdb:chip=avr128db48,clock=",
                                   "Curiosity Nano"),
                "avr16dd28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdd:chip=avr16dd28,clock=",
                                   "Breadboard"),
                "avr32dd28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdd:chip=avr32dd28,clock=",
                                   "Breadboard"),
                "avr64dd28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdd:chip=avr64dd28,clock=",
                                   "Breadboard"),
                "avr64dd32":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdd:chip=avr64dd32,clock=",
                                   "Curiosity Nano"),
                "avr16du28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdu:chip=avr16du28,clock=",
                                   "Breadboard"),
                "avr32du28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdu:chip=avr32du28,clock=",
                                   "Breadboard"),
                "avr64du28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdu:chip=avr64du28,clock=",
                                   "Breadboard"),
                "avr64du32":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrdu:chip=avr64du32,clock=",
                                   "Curiosity Nano"),
                "avr16ea28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrea:chip=avr16ea28,clock=",
                                   "Breadboard"),
                "avr32ea28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrea:chip=avr32ea28,clock=",
                                   "Breadboard"),
                "avr64ea28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrea:chip=avr64ea28,clock=",
                                   "Breadboard"),
                "avr64ea48":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avrea:chip=avr64ea48,clock=",
                                   "Curiosity Nano"),
                "avr16eb28":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avreb:chip=avr16eb28,clock=",
                                   "Breadboard"),
                "avr16eb32":  (tiny_updi_clock, ('huge', 'updi', 'noadc'),
                                   "DxCore:megaavr:avreb:chip=avr16eb32,clock=",
                                   "Curiosity Nano"),
                "avr32eb28":  (tiny_updi_clock, ('huge', 'updi', 'noadc', 'arduino'),
                                   "DxCore:megaavr:avreb:chip=avr32eb28,clock=",
                                   "Breadboard"),
                "avr32sd32":  (tiny_updi_clock, ('huge', 'updi', 'noadc', 'nonarduino'),
                                   "DxCore:megaavr:avrsd:chip=avr32sd32,clock=",
                                   "Curiosity Nano"),

                    }
