#pylint: disable=missing-module-docstring
# Clock combinations and naming
micro_clock = {'1.2' : ('1M2', '1200000UL'), '9.6' : ('9M6', '9600000UL'),
                   '16' : ('16M', '16000000UL')}
mini_clock = {'1' : ('1MHz_internal', '1000000UL'), '8' : ('8MHz_internal', '8000000UL'),
                  '16' : ('16MHz_external', '16000000UL')}
new_attiny_rc_clock = {'1' : ('internal_1m', '1000000UL'), '8' : ('internal_8m', '8000000UL')}
attiny_rc_clock = {'1' : ('1internal', '1000000UL'), '8' : ('8internal', '8000000UL')}
new_attiny_clock = {'1' : ('internal_1m', '1000000UL'), '8' : ('internal_8m', '8000000UL'),
                        '16' : ('external_16m', '16000000UL')}
attiny_clock = {'1' : ('1internal', '1000000UL'), '8' : ('8internal', '8000000UL'), '16': ('16external', '16000000')}
c_clock = {'1' : '1000000UL', '8' : '8000000UL', '16' : '16000000UL'}
no_clock = {'none' : ('', '16000000UL')}

# Tag list: for each tag in the list for one device, this tag has to be present in the script tag list
# Example: For attiny13 only scripts are selected that have  'small', 'arduino', 'dw'. and 'noadc' in their description
test_devices = {"attiny13" : (micro_clock, ('small', 'arduino', 'dw', 'noadc', 'noautopc'),
                                   "MicroCore:avr:13:clock=", "Dev Board"),
                "oldattiny2313" : (attiny_clock, ('small',  'dw', 'noadc', 'noautopc'),
                                   "ATTinyCore:avr:attinyx313:chip=2313,clock=", "Programmer-ZF"),
                "attiny2313" : (new_attiny_clock, ('small',  'dw', 'noadc', 'noautopc'),
                                   "ATTinyCore:avr:attinyx313:chip=2313,clock=", "Programmer-ZF"),
                "attiny2313a" : (attiny_clock, ('small',  'dw', 'noadc', 'noautopc'),
                                   "ATTinyCore:avr:attinyx313:chip=2313,clock=", "Programmer-ZF"),
                "oldattiny4313" : (attiny_clock, ('medium',  'dw', 'noadc', 'noautopc'),
                                   "ATTinyCore:avr:attinyx313:chip=4313,clock=", "Programmer-ZF"),
                "attiny4313" : (new_attiny_clock, ('medium',  'dw', 'noadc', 'noautopc'),
                                   "ATTinyCore:avr:attinyx313:chip=4313,clock=", "Programmer-ZF"),
                "oldattiny43u" : (attiny_rc_clock,  ('medium', 'dw', 'noautopc', 'noadc'),
                                   "ATTinyCore:avr:attiny43:clock=", "Breakout Board"), # changed name with v2.0.0!
                "attiny43u" : (new_attiny_rc_clock,  ('medium', 'dw', 'noautopc', 'noadc'),
                                   "ATTinyCore:avr:attiny43u:clock=", "Breakout Board"), # changed name with v2.0.0!
                "attiny24" : (attiny_clock, ('small',  'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx4:chip=24,clock=", "Dev Board"),
                "attiny44" : (attiny_clock, ('medium',  'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx4:chip=44,clock=", "Dev Board"),
                "oldattiny84" : (attiny_clock, ('large',   'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx4:chip=84,clock=", "Dev Board"),
                "attiny84" : (new_attiny_clock, ('large',   'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx4:chip=84,clock=", "Dev Board"),
                "oldattiny841" : (attiny_rc_clock, ('large',   'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx41:chip=841,clock=", "Breakout Board"),
                "attiny841" : (new_attiny_rc_clock, ('large',   'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx41:chip=841,clock=", "Breakout Board"),
                "attiny441" : (attiny_rc_clock, ('medium',  'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx41:chip=441,clock=", "Breadboard setup"),
                "attiny25" : (attiny_clock, ('small',   'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx5:chip=25,clock=", "Dev Board"),
                "attiny45" : (attiny_clock, ('medium',  'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx5:chip=45,clock=", "Dev Board"),
                "oldattiny85" : (attiny_clock, ('large', 'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx5:chip=85,clock=", "Dev Board"),
                "attiny85" : (new_attiny_clock, ('large', 'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx5:chip=85,clock=", "Dev Board"),
                "attiny261" : (attiny_clock, ('small',  'dw', 'noautopc'),
                                    "ATTinyCore:avr:attinyx61:chip=261,clock=", "Dev Board"),
                "attiny461" : (attiny_clock, ('medium',   'dw', 'noautopc'),
                                    "ATTinyCore:avr:attinyx61:chip=461,clock=", "Dev Board"),
                "oldattiny861" : (attiny_clock, ('large',   'dw', 'noautopc'),
                                    "ATTinyCore:avr:attinyx61:chip=861,clock=", "Dev Board"),
                "attiny861" : (new_attiny_clock, ('large',   'dw', 'noautopc'),
                                    "ATTinyCore:avr:attinyx61:chip=861,clock=", "Dev Board"),
                "oldattiny87" : (attiny_clock, ('large',  'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx7:chip=87,clock=", "Breakout Board"),
                "attiny87" : (new_attiny_clock, ('large',  'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx7:chip=87,clock=", "Breakout Board"),
                "attiny167" : (attiny_clock, ('large',  'dw', 'noautopc'),
                                    "ATTinyCore:avr:attinyx7:chip=167,clock=", "Breakout Board"),
                "attiny48" : (attiny_rc_clock, ('medium',  'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx8:chip=48,clock=", "Programmer-ZF"),
                "oldattiny88" : (attiny_rc_clock, ('large',  'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx8:chip=88,clock=", "Programmer-ZF"),
                "attiny88" : (new_attiny_rc_clock, ('large',  'dw', 'noautopc'),
                                   "ATTinyCore:avr:attinyx8:chip=88,clock=", "Programmer-ZF"),
                "oldattiny828" : (attiny_rc_clock, ('large',   'dw', 'noautopc'),
                                    "ATTinyCore:avr:attiny828:clock=", "Breakout Board"),
                "attiny828" : (new_attiny_rc_clock, ('large',   'dw', 'noautopc'),
                                    "ATTinyCore:avr:attiny828:clock=", "Breakout Board"),
                "oldattiny1634" : (attiny_rc_clock, ('large',  'dw', 'noautopc'),
                                     "ATTinyCore:avr:attiny1634:clock=", "Breakout Board"),
                "attiny1634" : (new_attiny_rc_clock, ('large',  'dw', 'noautopc'),
                                     "ATTinyCore:avr:attiny1634:clock=", "Breakout Board"),
                "atmega48" : (mini_clock, ('dirty', 'dw'),
                                    "MiniCore:avr:48:variant=modelNonP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega48a" : (mini_clock, ('medium',  'dw', 'noautopc'),
                                    "MiniCore:avr:48:variant=modelNonP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega48p" : (mini_clock, ('medium',  'dw', 'noautopc'),
                                    "MiniCore:avr:48:variant=modelP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega48pa" : (mini_clock, ('medium',  'dw', 'noautopc'),
                                    "MiniCore:avr:48:variant=modelP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega48pb" : (mini_clock, ('medium',  'dw', 'noautopc'),
                                    "MiniCore:avr:48:variant=modelPB,bootloader=no_bootloader," +
                                    "clock=", "TQFP socket on breadboard"),
                "atmega88" : (mini_clock, ('dw', 'dirty'),
                                    "MiniCore:avr:88:variant=modelNonP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega88a" : (mini_clock, ('large', 'arduino', 'dw', 'noautopc'),
                                    "MiniCore:avr:88:variant=modelNonP,bootloader=no_bootloader," +
                                    "clock=", "Programmer-ZF"),
                "atmega88p" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:88:variant=modelP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega88pa" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:88:variant=modelP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega88pb" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:88:variant=modelPB,bootloader=no_bootloader,clock=",
                                    "TQFP socket on breadboard"),
                "atmega168" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:168:variant=modelNonP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega168a" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:168:variant=modelNonP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega168p" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:168:variant=modelP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF / XPLAINED Mini Board"),
                "atmega168pa" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:168:variant=modelP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega328" : (mini_clock, ('large',  'dw', 'noautopc'),
                                    "MiniCore:avr:328:variant=modelNonP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZF"),
                "atmega328p" : (mini_clock, ('large',  'dw'),
                                    "MiniCore:avr:328:variant=modelP,bootloader=no_bootloader,clock=",
                                    "Programmer-ZIF"),
                "atmega328pb" : (mini_clock, ('large',  'dw'),
                                    "MiniCore:avr:328:variant=modelPB,bootloader=no_bootloader,clock=",
                                     "XPLAINED Mini Board"),
                "atmega168pb" : (mini_clock, ('large',  'dw'),
                                    "MiniCore:avr:168:variant=modelPB,bootloader=no_bootloader,clock=",
                                    "TQFP socket on breadboard / XPLAINED Mini Board"),

                # debugWIRE targets with no Core support
                "at90usb162" : (c_clock, ('large', 'nonarduino', 'dw', 'noadc', 'noautopc'), "",
                                    "AVR-USB-162 Olimex board"),

                # JTAG targets: MightyCore
                "atmega16" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:16:bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega16a" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:16:bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega32" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:32:bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega164pa" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:164:variant=modelP,bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega324p" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:324:variant=modelP,bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega644" : (mini_clock, ('large',  'jtag'),
                                     "MightyCore:avr:644:variant=modelA,bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega1284p" : (mini_clock, ('huge',  'jtag'),
                                     "MightyCore:avr:1284:variant=modelP,bootloader=no_bootloader,clock=",
                                     "MightyCore development board"),
                "atmega324pb" : (mini_clock, ('large', 'jtag'),
                                     "MightyCore:avr:324:variant=modelPB,bootloader=no_bootloader,clock=",
                                     "XPLAINED Pro Board"),

                # JTAG targets: MegaCore
                "atmega2560": (mini_clock, ('huge',  'jtag'),
                                   "MegaCore:avr:2560:bootloader=no_bootloader,clock=",
                                   "Arduino Mega"),
                "atmega1280": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:1280:bootloader=no_bootloader,clock=",
                                   "Arduino Mega 1280"),
                "atmega640": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:640:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega169p": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:169:variant=modelP,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega329p": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:329:variant=model329P,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega649a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:649:variant=model649,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega3290a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:329:variant=model3290,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega6490a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:649:variant=model6490,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega64": (mini_clock, ('large', 'jtag'),
                                   "MegaCore:avr:64:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega128": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:128:bootloader=no_bootloader,clock=",
                                   "Olimex AVR-MT-128 or Enplas socket"),
                "atmega1281": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:1281:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega2561": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:2561:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "at90can64": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:can64:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "at90can32": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:can32:bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "at90can128": (mini_clock, ('huge',   'jtag'),
                                   "MegaCore:avr:can128:bootloader=no_bootloader,clock=",
                                   "Olimex AVR-CAN"),
                "atmega165pa": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:165:variant=modelP,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega325a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:325:variant=model325,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega645a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:645:variant=model645,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega3250pa": (mini_clock, ('large', 'jtag'),
                                   "MegaCore:avr:325:variant=model3250P,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),
                "atmega6450a": (mini_clock, ('large',   'jtag'),
                                   "MegaCore:avr:645:variant=model6450,bootloader=no_bootloader,clock=",
                                   "Enplas socket"),


                # JTAG targets: MajorCore
                "atmega162": (mini_clock, ('large',  'jtag', 'noadc'),
                                   "MajorCore:avr:162:bootloader=no_bootloader,clock=",
                                   "Breadboard"),

                # JTAG targets: Arduino AVR Core
                "atmega32u4": (no_clock, ('large', 'jtag'),
                                   "arduino:avr:leonardo",
                                   "Leonardo"),

                    }
