# Triggered by a new release, it will do a basic check on version number and unit tests.
# Then it will build the binaries and creates the binary release assets and the downloadable tools for Arduino
# Finally, it will upload the new version to PyPI
name: Release workflow

on:
  release:
    types: [published]
  workflow_dispatch: # to run it manually

jobs:
  check:
    defaults:
      run:
        shell: bash
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        if: ${{ github.event.release.tag_name != '' }}
        uses: actions/checkout@v4

      - name: Set up python
        if: ${{ github.event.release.tag_name != '' }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        if: ${{ github.event.release.tag_name != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install .  # Install dependencies

      - name: Test tag against system version
        if: ${{ github.event.release.tag_name != '' }}
        run: |
          VER=$(python pyavrocd/main.py -V)
          VERSTRING=v${VER#*version }
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "System version string: $VERSTRING"
          echo "Github tag: $TAG_NAME"
          if [ "x$TAG_NAME" == "x" ]; then
             TAG_NAME=$VERSTRING
             echo "Adapted GitHub tag name to system version string"
          fi
          if [ "x$VERSTRING" != "x$TAG_NAME" ]; then
             echo "Release version does not match system version"
             exit 1
          fi
          echo "Release and system version are identical, now we continue"

      - name: Run unit-tests
        if: ${{ github.event.release.tag_name != '' }}
        run: |
          pytest

  build-binaries:
    needs: check
    strategy:
      matrix:
      # If you change something in the list of OSs, you also have to do it further down!
       os: [ "ubuntu-22.04", "macos-13", "windows-2022",  "ubuntu-22.04-arm",  "macos-14" ]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # Install dependencies

      - name: Package PyAvrOCD with PyInstaller
        run: |
          pyinstaller -y pyavrocd.spec

      - name: Upload as artifact (macOS ARM = macos-14)
        if: matrix.os == 'macos-14'
        uses: actions/upload-artifact@v4
        with:
          name: arm64-apple-darwin
          path: dist/pyavrocd/*
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Upload as artifact (Linux Arm = ubuntu-22.04-arm)
        if: matrix.os == 'ubuntu-22.04-arm'
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-linux-gnu
          path: dist/pyavrocd/*
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Upload artifact (Windows Intel = windows-2022)
        if: matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-mingw32
          path: dist/pyavrocd/*
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Upload artifact (macOS Intel = macos-13)
        if: matrix.os == 'macos-13'
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: dist/pyavrocd/*
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Upload artifact (Linux Intel = ubuntu-22.04)
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux-gnu
          path: dist/pyavrocd/*
          overwrite: true
          include-hidden-files: true

  upload:
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Download arm64-apple-darwin
        uses: actions/download-artifact@v5
        with:
          name: arm64-apple-darwin
          path: extras/binaries/arm64-apple-darwin

      - name: Download aarch64-linux-gnu
        uses: actions/download-artifact@v5
        with:
          name: aarch64-linux-gnu
          path: extras/binaries/aarch64-linux-gnu

      - name: Download x86_64-mingw32
        uses: actions/download-artifact@v5
        with:
          name: x86_64-mingw32
          path: extras/binaries/x86_64-mingw32

      - name: Download x86_64-apple-darwin
        uses: actions/download-artifact@v5
        with:
          name: x86_64-apple-darwin
          path: extras/binaries/x86_64-apple-darwin

      - name: Download x86_64-linux-gnu
        uses: actions/download-artifact@v5
        with:
          name: x86_64-linux-gnu
          path: extras/binaries/x86_64-linux-gnu

      - name: Packing
        run: bash extras/packer.sh

#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: extras/avrocd-tools
#          target-folder: avrocd-tools

      - name: Asset upload
        uses: softprops/action-gh-release@v2
        with:
          files: extras/assets/*.tar.gz

  build-pypi-distribution:
    name: Build distribution
    needs: upload
    runs-on: ubuntu-latest

    steps:
    - run: exit 1

    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: >-
      Publish Python distribution to PyPI
    needs:
    - build-pypi-distribution
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/PyAvrOCD  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
