name: Linting, unit tests and coverage

on:
  workflow_dispatch: # to run it manually
  push:
    paths:
      - '**.py'
    branches:
      - 'main'
  pull_request:


jobs:
  check:
    defaults:
      run:
        shell: bash
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-pip-wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - name: Unit tests
        run: |
          source $VENV
          echo "PYLINT="`pylint -f json2 pyavrocd | python -c "import sys, json; print(json.load(sys.stdin)['statistics']['score'])"` >> $GITHUB_ENV
          pytest  --junitxml=pytest.xml --cov-report=term-missing:skip-covered
      - name: Pytest coverage comment
        if: always()
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
      - name: Result evaluation
        if: always()
        run: |
          echo "PYTESTPERCENT="`python -c "import xml.etree.ElementTree as ET; el = ET.parse('pytest.xml').find('./testsuite'); tests=int(el.attrib['tests'])-int(el.attrib['skipped']); failed=int(el.attrib['errors'])+int(el.attrib['failures']); print('%.1f' % (100 - (failed/tests)*100))"`  >> $GITHUB_ENV
          echo "PYTESTCNT="`python -c "import xml.etree.ElementTree as ET; el = ET.parse('pytest.xml').find('./testsuite'); tests=int(el.attrib['tests'])-int(el.attrib['skipped']); print(tests)"`  >> $GITHUB_ENV
          echo "PYCOV="`python -c "import json; js=open('cov.json'); print('%.1f' % json.load(js)['totals']['percent_covered'])"` >> $GITHUB_ENV
      - name: Generate Pylint label
        if: always()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: c0d539e3ad0d10252d2aab8ad325246a
          filename: pylint.json
          label: pylint
          namedLogo: Python
          logoColor: white
          message: ${{ env.PYLINT }}
          valColorRange: ${{ env.PYLINT }}
          maxColorRange: 10.0
          minColorRange: 0
      - name: Generate Pytest label
        if: always()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: c0d539e3ad0d10252d2aab8ad325246a
          filename: pytest.json
          label: pytest
          namedLogo: Pytest
          logoColor: white
          message: "${{ env.PYTESTCNT }}: ${{ env.PYTESTPERCENT }}%"
          valColorRange: ${{ env.PYTESTPERCENT }}
          maxColorRange: 100.0
          minColorRange: 30.0
      - name: Generate coverage label
        if: always()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: c0d539e3ad0d10252d2aab8ad325246a
          filename: pycov.json
          label: coverage
          namedLogo: Pytest
          logoColor: white
          message: "${{ env.PYCOV }}%"
          valColorRange: ${{ env.PYCOV }}
          maxColorRange: 90.0
          minColorRange: 30.0