name: Upload

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: asset upload
        run: |
          sudo apt install hub
          tag_name=${{ github.event.release.tag_name }}
          set -x
          assets=()
          for asset in extras/assets/*; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}