name: Upload

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  upload:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Where
        run: |
          pwd
          ls -la

      - name: Upload asset for Linux/ARM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: extras/assets/pyavrocd-binary-aarch64-linux-gnu.tar.gz
          asset_name: pyavrocd-binary-aarch64-linux-gnu.tar.gz
          asset_content_type: application/gzip

      - name: Upload asset for Linux/Intel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: extras/assets/pyavrocd-binary-x86_64-linux-gnu.tar.gz
          asset_name: pyavrocd-binary-x86_64-linux-gnu.tar.gz
          asset_content_type: application/gzip

      - name: Upload asset for Windows/Intel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: extras/assets/pyavrocd-binary-x86_64-mingw32.tar.gz
          asset_name: pyavrocd-binary-x86_64-mingw32.tar.gz
          asset_content_type: application/x-gzip